import * as fs from 'fs';
import * as path from 'path';
import { findMonorepoRoot } from './find-root';

const ROOT = findMonorepoRoot(__dirname);
const EXCHANGES_DIR = path.join(ROOT, 'libs/types/src/lib/amqp/exchanges');
const OUTPUT_FILE = path.join(
  ROOT,
  'libs/types/src/lib/amqp/exchange.config.ts',
);

// 🔍 Read all *.exchanges.ts files
const files = fs
  .readdirSync(EXCHANGES_DIR)
  .filter((f) => f.endsWith('.exchanges.ts'));

// ✍️ Build imports and map
const imports: string[] = [];
const mapEntries: string[] = [];

for (const file of files) {
  const service = file.replace('.exchanges.ts', '');
  const varName = `${service.toUpperCase()}_EXCHANGES`;
  imports.push(`import { ${varName} } from './exchanges/${file}';`);
  mapEntries.push(`  ${service}: ${varName},`);
}

const output = `// 🔄 Auto-generated by generate-exchange-config.ts
${imports.join('\n')}

export const SERVICE_EXCHANGE_MAP = {
${mapEntries.join('\n')}
} as const;
`;

fs.writeFileSync(OUTPUT_FILE, output);
console.log(`✅ Generated SERVICE_EXCHANGE_MAP in ${OUTPUT_FILE}`);
